# Generated by Django 5.0.1 on 2024-03-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakeshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="flavour_object",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cakeshop.flavour",
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="occasion_object",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cakeshop.occasion",
            ),
        ),
    ]
