# Generated by Django 5.0.1 on 2024-03-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakeshop", "0002_basketitem_flavour_object_basketitem_occasion_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="is_order_placed",
            field=models.BooleanField(default=False),
        ),
    ]
