# Generated by Django 5.0.1 on 2024-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakeshop", "0004_alter_basket_owner_alter_basketitem_basket_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
